name: Swift

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
